theme: jekyll-theme-architect

title: AWS Consulting

description: Cloud Architecture and DevOps

author: Yuri Nemchin

github:
  is_project_page: false
  
site:
  github:
    owner_url: https://www.techops.space
    is_project_page: False
    is_user_page: False

linkedin_badge: |
  <script src="https://platform.linkedin.com/badges/js/profile.js" async defer type="text/javascript"></script>
  <div class="badge-base LI-profile-badge" data-locale="en_US" data-size="medium" data-theme="light" data-type="VERTICAL" data-vanity="your-cloud-architect" data-version="v1"><a class="badge-base__link LI-simple-link" href="https://fi.linkedin.com/in/your-cloud-architect?trk=profile-badge">Yuri</a></div>
