remote_theme: wildaxe/architect

title: Cloud Consulting

description: Architecture and DevSecOps

author: Yuri Nemchin

github:
  is_project_page: false
  
site:
  github:
    owner_url: https://www.techops.space
    is_project_page: False
    is_user_page: False
